### ISSUE TITLE
SMBIOS information decoding and printing

### ISSUE THREAD

**Issue by debrouxl** [memtest86plus/memtest86plus#1]
Older memtest86+ versions support printing a small subset of DMI / SMBIOS information. On many computer models, this information is known to be incomplete or inaccurate (serial numbers for memory chips, number of memory devices, etc.), but I tend to think that it's nice to have a way to view part of it, without having to boot a full-blown general purpose OS.
The existing memtest86+ code is both limited and unreliable: for instance, it contains an easy to hit buffer overflow, fixed downstream and reintegrated into at least https://github.com/anphsw/memtest86/commit/d15092a56940810b6e124d59c20c819e5e3e7df1 fork.

In order not to reinvent the wheel and hopefully minimize the maintenance cost, I had a short look at dmidecode's GPLv2 source code, aiming at examining the creation of a derivative with the following characteristics:
* freestanding, for integration of the parsing and decoding code into memtest86+ (displaying the information in 80x25 mode is another matter, some structs would require vertical scrolling);
* reduced decoding, because a memory testing tool had better be small, and it doesn't need to decode every SMBIOS struct type or even every single field of a relevant struct type:
    * 0 BIOS Information, currently unhandled by memtest86+;
    * 1 System Information, currently unhandled;
    * 2 Baseboard / Module information, handled;
    * 4 Processor Information, handled;
    * maybe 5 Memory Controller Information and 6 Memory Module Information, obsolete and currently unhandled, but that's all some
~20-year-old motherboards - on which testing old memory sticks also makes sense - have to offer;
    * 16 Physical Memory Array, unhandled;
    * 17 Memory Device belonging to a Physical Memory Array, handled;
    * 18 32-bit Memory Error information, unhandled;
    * maybe 19 Memory Array Mapped Address, unhandled;
    * 20 Memory Device Mapped Address, handled;
    * 33 64-Bit Memory Error Information, unhandled;
    * 37 Memory Channel, unhandled.

The obvious way to remove functionality is to litter the dmidecode source code with #ifdef / #endif pairs, and it probably wouldn't even be high maintenance as dmidecode's source code doesn't have a high rate of change, but meh. If / when embarking on this journey, we should probably contact the dmidecode maintainer, who I already worked with when fuzzing dmidecode - maybe there's something slightly better to be done for both upstream and downstreams.

On the memtest86+ side, maybe we shouldn't even care about maximum, fine-grained reduction of the DMI decoding capabilities, since dmidecode isn't a huge binary to begin with, e.g. on my computer's Debian sid amd64:
```
# ls -l /usr/sbin/dmidecode
-rwxr-xr-x 1 root root 117608 20 août  08:15 /usr/sbin/dmidecode
```
Still, we could save several dozen kilobytes on that.

**Comment by x86fr** [comment]
Even if we should not reinvent the wheel (aka `dmi-decode`), I agree that Full SMBIOS DMI decoding (tens of tables) and Full SPD decoding (hundreds of options) would be nice, and they're quite easy to decode (just by adding the corresponding structs). The biggest issue is to write the code to display all these information efficiently. That will probably require a switch to graphic mode and a "pre-boot" menu with dedicated sub-menus. 

Also, we must keep real user's priorities in mind, because dev resources are limited. To date, nobody asked me to add full DMI or SPD decoding functions. I got one request for some additional DMI fields (maybe 3/4) but with low priority and I don't really see a real-world scenario where others fields can be useful. In the opposite, they're all screaming for a way to write a log file to a USB drive (unattended execution in a test chain is the top priority for many users in industrial environments ; that's why they wanted Serial/RS232 feature back as soon as possible). Adding a Rowhammer test is also high on the top list. And solving issues (I just get an annoying bug report on Hybrid CPUs that will require some fix) before the first final release.

So basically, we have 3 options if we really want to spend time on more DMI decoding:

1. Start working on graphic mode to handle all new datas in a clean way
2. Add a Quick&Dirty way to display some reduced DMI Fields by using the config menu
3. Add a new popup dedicated to a reduced DMI information

**Comment by debrouxl** [comment]
Option 1 is a lot of work, though important for the mid- and long-term.
Option 2 is Q&D work which would have to be redone properly later.
Option 3 provides a useful building block for those who don't want to, or can't, use graphic mode, so it's not precluded by option 1.

=> option 3 first and option 1 later, IMO :)

But indeed, at lower priority than a number of other tasks, unless of course, someone wants to work on this feature, along the lines of:
* enlarging, moving and exporting app/config.c::popup_save_buffer;
* adding partial decoding and printing code for the several relevant DMI struct types of lowest numeric IDs, probably derived from `dmidecode`. Types 0, 1, 2 and even 4 don't require vertical scrolling when not decoding the bit fields of questionable usefulness. I can provide the code to slash down decoding in dmidecode.c, it's nothing secret or complicated - I still haven't found a convincing way to reduce the footprint at compile time without spraying #ifdef / #endif pairs throughout the code;
* adding code for switching between the standard memory testing mode, the config mode and the DMI data decoding mode upon keypresses;
* adding code for switching between DMI data struct instances, on different pages, upon keypresses;
* etc.
