### ISSUE TITLE
Memtest86+ version for PowerPC

### ISSUE THREAD

**Issue by InfoLibre** [memtest86plus/memtest86plus#143]
Could you add a Memtest86+ versions for 32/64 bit PowerPC, included little-endian and big-endian? Then, it could be added to GRUB in this distribution: https://cdimage.debian.org/cdimage/ports/snapshots/

**Comment by martinwhitaker** [comment]
Speaking for myself, no. Memtest86+ contains a lot of x86 CPU and platform specific code (the clue's in the name!). Porting to PowerPC would be a big task, and I have no PowerPC hardware to test it on.

**Comment by InfoLibre** [comment]
If you decide to port it to PowerPC, I can give you this iMac G3 with 1 GB RAM: https://everymac.com/systems/apple/imac/specs/imac_dv_se_500.html

And I can take time to organize a donation campaign if you need to buy other models.

Indeed, you will need to rename Memtest86+ into Memtest86+PPC or something like that :)

**Comment by InfoLibre** [comment]
There's this project: https://www.powerpc-notebook.org/fr/
And a community: https://www.powerprogress.org/en/

**Comment by debrouxl** [comment]
Yeah, that's what I was going to post as well :)
Porting memtest86+ - or pretty much any other code base, in general - to various pieces of exotic hardware could undoubtedly be considered nice by some of the users of said pieces of exotic hardware, but that takes equipment, possibly significant amounts thereof, and work, again significant amounts thereof... As such, in order to maximize usefulness to real-world users, better spend time on more widespread hardware first... ARM-based hardware being by far the most obvious candidate, though historically, ARM hardware was, and still is to some extent, poorly standardized.
