### ISSUE TITLE
Serial console support

### ISSUE THREAD

**Issue by debrouxl** [memtest86plus/memtest86plus#15]
Serial console support is useful in some enterprise setups. Older servers' BMCs often have serial ports.

**Comment by lvd2** [comment]
Just to add up: even a headless desktop running as "home server" would benefit from serial console.

**Comment by x86fr** [comment]
Serial console support is clearly a high priority. I'm working on memory modules detection on AMD Ryzen platform, then I'll switch to serial console support.

**Comment by x86fr** [comment]
Started working on serial support. The planned timing strategy based on previous reports will be :

- Full screen redraw after every test (to clear potential transmit issues)
- Instant error reporting
- Timed partial redraw (only lines like test/pass status, errors, time, temperature, etc) every **X** seconds.

X will be configurable with a default set at 2 seconds.

**Comment by x86fr** [comment]
WIP! ☺

![image](https://user-images.githubusercontent.com/38105886/160514282-630587a5-eee4-4ba9-a23d-18349a9fdd31.png)

**Comment by x86fr** [comment]
Preliminary TTY support added. Code is not final but I pushed the first commit because many files changed. 

Serial TTY can be enable by setting `enable_tty = true` in `config.c` or by passing argument at startup.

Expected argument is like `console=ttySx,y` with `x` being the serial port address (0 = 0x3F8 / 1 = 0x2F8 / 2 = 0x3E8 / 3 = 0x2E8) and `y` an optional single digit representing the baud rate (0 = 9600, 1 = 19200, 2 = 38400, 3 = 57600, 4 = 115200). Default is 0x3F8 and 115200. I will probably add support for custom or faster baud rate in the future.

I don't think I will add support for anything other than 8-data bit / no parity / 1 stop bit because I can't remember any modern PC or server (less than 30 years old) that default to any other setting. 

A full screen dump is done at startup, then only partial refreshes every x seconds (for lines that changed like tests status or errors). The faster the baud rate, the more often the refreshes : from every 2 secs at 115200 bps to every 5 secs at 9600 bps. Code is optimized to send only few bytes to UART as possible for refreshes.

TTY keyboard works but not past the first menu level (WIP).

We should probably consider a change for the keys used because VT100 terminal doesn't have F1-F12 functions keys. Maybe revert to "s" for setup and 0-9 for browsing between menus. They're already mapped, but maybe it will be better to invert keys (0-9 displayed and F1-F9 hidden)

I tested this on real hardware with a RS232 <-> USB adapter and Teraterm. Any tests on servers welcome! :)

**Comment by martinwhitaker** [comment]
Don't use 's' (or any other letter) - that's awkward for people using non-Latin keyboard layouts. I preferred function keys over digits for the same reason, although that's a rarer case.

**Comment by x86fr** [comment]
Ah yes. Using number is also not ideal on some keyboard layout, especially on french keyboards where number are shifted.

What about "Enter" to enter and exist menus? It's as universal as "Esc" or "Space" and obviously available on VT100 keyboard.

**Comment by x86fr** [comment]
Merged

**Comment by Fantu** [comment]
> Expected argument is like `console=ttySx,y` with `x` being the serial port address (0 = 0x3F8 / 1 = 0x2F8 / 2 = 0x3E8 / 3 = 0x2E8) and `y` an optional single digit representing the baud rate (0 = 9600, 1 = 19200, 2 = 38400, 3 = 57600, 4 = 115200). Default is 0x3F8 and 115200. I will probably add support for custom or faster baud rate in the future.

I think that probably the readme should be updated and this explain included

**Comment by x86fr** [comment]
Yep! A README update is planned soon :)
