### ISSUE TITLE
USB keyboard not working

### ISSUE THREAD

**Issue by ikerrg** [memtest86plus/memtest86plus#183]
My PC is an OLD DELL Precision T7500 with a Xeon X5675 CPU (https://www.dell.com/support/home/en-uk/product-support/product/precision-t7500/drivers). Memtest boots and works fine, but I cannot change any option or restart the system after booting to it because my USB keyboard does not work. If you need any more info, just tell me. The system is the standard configuration for the one mentioned above, but with 60 GB or RAM (3*16GB+3x4GB DIMMs).
Regards.

**Comment by debrouxl** [comment]
Which version of memtest86+ are you using ? It's displayed at the bottom right of the screen.
When booting from some bootloader, could you pass the "usbdebug" parameter onto the memtest86+ command line, and post a picture of the screen where the USB controllers are listed ?
Thanks in advance :)

**Comment by ikerrg** [comment]
Hi. A screenshot is attached with the version used. 
![20221012_080041b](https://user-images.githubusercontent.com/6968371/195283201-d78218e5-b1b9-4a9a-b301-5ecd40857fc6.jpg)
Regarding the bootloader, I just used the Windows USB installer on a USB stick. If you tell me how to pass that parameter onto the commandline, I can do it.
Regards.

**Comment by martinwhitaker** [comment]
This has a legacy BIOS (not UEFI), yes? Check if there is an option to enable legacy USB support or legacy keyboard emulation in the BIOS setup menus.

**Comment by ikerrg** [comment]
Yes, it is BIOS, not UEFI. It also has a PS2 port for keyboards, which is usually much more compatible, but I am not using it. I'll check for that option in BIOS.

**Comment by ikerrg** [comment]
I cannot see any option for legacy USB or keyboard. I recall that option in other computers, but this is a DELL BIOS. But browsing through the BIOS, I saw a log with multiple ECC errors (correctable) from when memtest was running (in DIMM3). I might remove that DIMM and check again if more errors are logged in BIOS. It is a pity that memtest cannot show the ECC errors itself.

**Comment by debrouxl** [comment]
ECC/EDAC support is tracked by #92 , you can upvote that if you wish :)
But that computer is unlikely to see EDAC controller support in memtest86+ anytime soon, because it has a decade+-old processor family.

In general:
* implementing full support for at least a dozen families of controllers spanning well over a decade would be a huge amount of work: FWIW, the Linux EDAC drivers corresponding to x86/x86_64 EDAC controllers are made of well over 10K raw lines of code combined.
* reliably testing the result requires special hardware (2+ computers equipped with that controller model, and faulty RAM sticks which produce known ECC-correctable errors) and is therefore a lot of work as well.

**Comment by ikerrg** [comment]
I understand the effort required to code the ECC routines. I knew that they were chipset dependant, which makes them very difficult to support, especially for BIOS based computers (old, not UEFI, etc). No worries, at least BIOS is reporting the errors so I can detect them after memtest has triggered them.

**Comment by martinwhitaker** [comment]
To pass command line options to Memtest86+, you need to start it via an intermediate bootloader. The ISO with GRUB lets you do that. I don't know whether the Windows installer supports using that ISO - if not, you can use Rufus (make sure to select 'dd' mode when copying the ISO to the USB stick). When you boot from that ISO, at the GRUB menu press 'e' to edit the boot options, use the cursor keys to navigate to the end of the line starting `linux /boot/memtest`  and append ` keyboard=usb usbdebug`, then press Ctrl-X to start Memtest86+.

It's possible that just adding `keyboard=usb` will be enough to get your keyboard working - the default for legacy boot is to use the BIOS legacy keyboard emulation.

**Comment by ikerrg** [comment]
Yep! That worked like a charm!

The keyboard works perfectly after booting with GRUB (I wonder if it would work without the keyboard=usb modifier. In addition, memtest does not use the "Long Mode" to access all the RAM, it just uses the native x64 access like in UEFI systems, which I suppose it is better (faster?). Below you have the requested info.
Thanks a lot for your support!

![20221012_140222b](https://user-images.githubusercontent.com/6968371/195350519-c5e1ad00-3543-4f6e-96e7-4eef821a4ed4.jpg)

**Comment by gakimov** [comment]
Does not work here even with keyboard=usb. Mobo is Asus P12R-M
![Screen Shot 2022-10-12 at 4 57 04 PM](https://user-images.githubusercontent.com/18075405/195469089-4932414b-c29e-466c-881d-cd55c7373afd.png)

**Comment by debrouxl** [comment]
This XHCI controller is mapped above 4 GB, like the one in #180 , so its operation might be improved by the recent fix mentioned in that issue.
Are you able to build an updated image from the current source code ?

**Comment by gakimov** [comment]
Yes, I built it and it was impressively easy. Will try it again soon.

**Comment by martinwhitaker** [comment]
I changed the GRUB menu items on the grub-memtest,iso to be more useful for end-users rather than developers, so it now offers the choice of either using the built-in USB keyboard support or using USB legacy keyboard emulation as provided by the BIOS. The standard memtest.iso still defaults to using USB legacy keyboard emulation if you boot in legacy mode or to using the built-in USB keyboard support if you boot in UEFI mode. I think that's the best we can do - yes, on some machines, like the Dell here, the standard memtest.iso won't give a working keyboard, but if we change the default, it then won't work on other machines that have quirky USB devices. So closing this issue.

@gakimov , if you still have a problem, please open a new issue for that.

**Comment by rwuwon** [comment]
Mechanical keyboard users: If N-Key Rollover is enabled via a DIP switch, try turning that off. That was the case with my keyboard on memtest86+ 6.10, and it works fine when N-Key Rollover is disabled.
_(Commenting here for others since it's prominent in search results.)_

**Comment by martinwhitaker** [comment]
@rwuwon , if you are using Linux, can you:

1. Run `lsusb` to identify the vendor/device ID for your keyboard. For example, on my system I get the line
````
Bus 003 Device 002: ID 046d:c534 Logitech, Inc. Nano Receiver
````
2. Run `lsusb -d 046d:c534 -v`, replacing 046d:c534 with the ID for your keyboard.

If you can, please open a new issue and post the output from step 2 both when N-key rollover is enabled and when N-key rollover is disabled.
