### ISSUE TITLE
Do NOT use red cross!

### ISSUE THREAD

**Issue by maekawa-mugi** [memtest86plus/memtest86plus#188]
The Red Cross is used in some of the artwork on the website.
However, the Geneva Convention limits the use of the Red Cross to Red Cross Society use only.

Therefore, the Red Cross should not be used!

**Comment by x86fr** [comment]
A red cross being part of the Memtest86+ logo since 20+ years, this concern has been raised in the past. That was on the previous (now-closed) Memtest86+ support forum and unfortunately, I can't find a copy on archive.org, so here is a summary.

- Using a red cross alone, as a diminutive form, or in a form where the cross is bigger or a similar size as the "Memtest86" text (eg: big red cross and small text the width of the cross) is forbidden.
- According to the previous point, the current favicon on memtest.org and the current Github Memtest86+ Organization Avatar will be changed later today. That's a mistake.
- Use of a red cross **as part of** a bigger logo in the overall context of Memtest86+ is not illegal to the extent of my knowledge and according to the previous discussion we had on the subject. An email was sent to the ICRC when this concern was first risen in ~2010 and I get a reply saying basically "our legal team will let you know if this is an issue", without further reply.
- I make regular donations to the ICRC on my name and on behalf of Memtest86+ team. They're usually made with the Paypal account used for our own donation, and sent with the Memtest86+ logo. As of today, nobody complained.
- If we receive any complaint from ICRC for **using a red cross as part of the Memtest86+ logo**, we will obviously immediately change it (probably with a white cross and a red stroke, or even with a different color cross).

**Comment by x86fr** [comment]
Both favicon and github avatar have been replaced.
