### ISSUE TITLE
Donate button gives me something when wrong?

### ISSUE THREAD

**Issue by msetzerii** [memtest86plus/memtest86plus#251]
Something went wrong

You might be having a network connection problem, the link might be expired, or the payment provider cannot be reached at the moment.

https://checkout.stripe.com/c/pay/plink_1MKhk3C7XQHdydAdCpnbx94X#fidkdWxOYHwnPyd1blppbHNgWjA0SE5tUERGMl1UTWF8YURhTjdpMkFRQkZ9V2tMRzFufWExal80dF90cVdNaVI2NEZkVmNQN3VBbm5fUnxnR0BmXzJDYEpBZGxKRH10X1BXZzRvb313REBcNTV3aHFjSnE8dycpJ3VpbGtuQH11anZgYUxhJz8nNTViMnFdNkhKY0h9NHJcNmZmJyknd2BjYHd3YHdKd2xibGsnPydtcXF1dj8qKmhgaHFgdnErandiKid4JSUl

Is link with above message. Shows last donation as 12/03/2022, so seems it worked then?

**Comment by x86fr** [comment]
Some weeks ago, Paypal definitely banned without warning the 20 y/o account that was used to receive donation because they hate small amount transactions, especially for open-source projects (as it's considered "crowdfunding"). I tried to create another account with stripe, which was banned 48 hours later for the same reason. They told me they won't keep an account live for such small amounts (we need at least 500€/year).

So I'll remove the links entirely as there is no way to get donations anymore. I may set up a Git Hub Sponsor account.

This said, these donations were used almost exclusively to buy hardware (generally old stuff) to add support to Memtest86+, so sending the related hardware directly to us is an even better solution.

**Comment by msetzerii** [comment]
Strange? I've had a personnel paypal account for decades, and generally use it with ebay or amazon. I've also, sent money to other individuals for relatively small amounts. Not sure if it is because of a business versus personnel? Have found the 6.01 and now 6.10 work with Fedora 36/37 via grub2 menu. Even manually added to Fedora 37 install ISO, and with legacy boot it works, but any mode to iso make UEFI boot dump to shell..
Thanks for the updates.

**Comment by x86fr** [comment]
This Paypal account has been set up 20 years ago for the very first Memtest86+ v1.00 release. Paypal closed it and banned me without warning, seizing the ~100$ balance in the process. It seems that's quite common and there is nothing to do. After numerous phone call, I was told that "free open source software" is not a real business because it's free, and "donations" are now against their rules (except for proven charity).

**Comment by vazhnov** [comment]
@x86fr, I can recommend you to take a look at https://opencollective.com , which is my favorite about visibility of money flow and https://liberapay.com. Both are opensource.

**Comment by blathers123** [comment]
have you considered either https://www.buymeacoffee.com/ or https://www.patreon.com/ ?
Both are geared towards supporting smaller projects

**Comment by x86fr** [comment]
Donate button now removed. Will investigate other options later.
