### ISSUE TITLE
DELL Precision T3650 with SecureBoot on doesn't allow MemTest+ 6.10 to boot

### ISSUE THREAD

**Issue by H7dek7** [memtest86plus/memtest86plus#283]
On DELL Precision T3650 MemTest86+ 6.10 won't boot with SecureBoot turned on. After choosing MemTest86+ pendrive as boot device DELL's BIOS says "All bootable devices failed secure boot verification". Other DELL workstations with SecureBoot on in our company allow MemTest86+ 6.10 to boot. Disabling SecureBoot on T3650 is a workaround. All workstations have the latest BIOS.

**Comment by x86fr** [comment]
That's the expected behavior. While Memtest86+ 6.10 now supports Secureboot _signing_, the binary is not currently _signed_ by Microsoft. To use Memtest86+ 6.10 with a Secureboot-enabled computer, you have to sign the binary by yourself, then enroll the private key to your Secureboot key library ... or wait until we find a more universal solution on your side. We're working on it.
