### ISSUE TITLE
Add i386 support ?

### ISSUE THREAD

**Issue by tazgm** [memtest86plus/memtest86plus#307]
SliTaz add a patch for Memtest 6.20 https://hg.slitaz.org/wok/raw-file/tip/memtest/stuff/memtest86%2B-6-386.patch
The build is in https://cook.slitaz.org/index.cgi?browse=memtest/source/memtest-6.20/build32/  
 
It supports 386 motherboards with 1MB.

**Comment by debrouxl** [comment]
Hard to disagree with Sam, 386, 486 and compatible processors of the same generations processors being very ancient by now... I have used a physical 386 system around 2021, but still :)
However, I appreciate the effort as well, all the more it looks like some of the hunks in this patch, e.g. those in system/cpuinfo.c , system/cpuid.c and app/main.c , ought to be part of #120 , if that is ever merged.

Maybe some bits from #120 would prove useful to SliTaz as well, and maybe SliTaz should be mentioned on memtest.org as carrying an unofficial 386-compatible variant, not supported by upstream memtest86+ ?

**Comment by 01e3** [comment]
Most of the code seems non-problematic, for the rest - would it be acceptable to be guarded by something like a #ifdef? While I understand there is no desire to provide and especially support and 386-compatible binary, it would enable anyone to compile a 386-working version on their own.

And yes, I'm planning to go back to https://github.com/memtest86plus/memtest86plus/pull/120 very soon, once my PTO starts in several weeks...

**Comment by x86fr** [comment]
Definitely no. This is a nonsense for general use, and for various reasons

1. No 386-class CPUs supports CPUID. This is a late 486 instruction. The only CPU for 386 socket that supports CPUID is the Cyrix Cx486SLC/DLC, which is a 486-class CPU
2. Limiting to 1 MB doesn't make sense. The 386 is 32 bits and supports up to 4 GB of RAM (usually up to 16 MB in real-world hardware).
3. Most important: On real-world hardware, Memtest86+ v6 has nothing to offer versus an older version (let's say v2.11) with such old processor. Even worst: using v6 can be counter-productive as it can fail to detect memory issue while v2.11 will catch them. This is due to the lack of relocation with such low memory due to the binary+stack / memory capacity ratio, which is much higher on v6 versus v2.

**Comment by tazgm** [comment]
FYI 
 1. Early 486 doesn't support CPUID.
 2. Early cheap 386sx motherboards had 1MB only in discrete chips and most 386sx motherboards were sold with 2x1MB RAM.
 3. Memtest86+ v2.11 needs 4MB.

**Comment by 01e3** [comment]
Sure Sam, all valid points so no disagreement here. However, a part of my point it that there is a pretty large (and growing?) "Retro PC" community and I would expect people to be really excited to see a modern, free Memtest86+ working there, with a lot of fixes, improved Serial support, etc.

BTW: the code does not seem to limit the RAM to 1MB, it only changes the load address and "split" for relocation to support systems with only 1MB. Anyway, we can skip this part (at least for now?) if too controversial. I think even for the Retro use case, we can start with some slightly stronger HW requirements.. ;)

So, I think the main change is handling the lack of CPUID and cache (and no instructions like wbinvd). If I find a clean(er?) way to implement it, how hard would be to convince you to include it? ;)
