### ISSUE TITLE
Memtest86+ is not starting

### ISSUE THREAD

**Issue by Oneinunity** [memtest86plus/memtest86plus#318]
I don't get what's happening. I'm currently on Windows 11 and I have countless times installed and used memtest86+ on a usb stick without issues, but whatever I do, the computer now boots from the stick and instead of memtest86+ I end up in GRUB. 

I do not know how to proceed from there or how to solve the issue. I even went back to a previous version that never gave problems before, but it leads to the same behaviour.

Using ASUS Prime Z690P WIFI MB / Intel Core i5-12600KF

Any ideas?

![2023-06-19 02 25 32](https://github.com/memtest86plus/memtest86plus/assets/137014572/27065d5d-3dad-4a3b-92ae-1e497edf8d4b)

**Comment by x86fr** [comment]
Are you sure Secureboot is disabled?

**Comment by Bahram-Alinezhad** [comment]
It's not related to secure boot because otherwise it couldn't come to grub. When grub is loaded from disk, it means UEFI or BIOS has passed the boot sequence to disk.
This problem is usually related to grub in accessing its configuration file.
Unfortunately I'm not familiar with grub-pc, however, I can only say if it was grub-legacy or grub-for-dos, a "root" command would show what is current root device and then a "configfile <file>" command could be used to load the proper configuration file for running memtest.
Someone may guide about similar commands for grub-pc.
As user says:
"I have countless times installed and used memtest86+ on a usb stick without issues",
My guess is that a problem of bad sector of usb flash disk has made grub's config file (or memtest kernel) unreadable.

**Comment by x86fr** [comment]
That's not how secureboot works. It's a trust of chain. If Secureboot is enabled and Grub is signed, it will load Grub but Grub will fail to load an unsigned binary (while correctly loading a signed binary against grub like a linux kernel). Anyway, maybe you should try another USB drive if you think it may be faulty.

**Comment by Oneinunity** [comment]
After a while I installed memtest86+ on a new usb-stick and to my amazement it worked as usual. I waited a while with posting this result over here because I have installed the program countless times on the first stick and the stick shows no problems at all if I use it for other purposes, so I intended to find out more about it. But unfortunately I lack the time. So I conclude that nothing is wrong with the program or the installer and the problem was caused by "something" on the other usb-stick and close the issue.
