### ISSUE TITLE
3000mt/s overclocked to 3200mt/s

### ISSUE THREAD

**Issue by bjlockie** [memtest86plus/memtest86plus#324]
I have ddr4 that has a 3000mt/s XMP2 profile but I'm trying it at 3200mt/s so I manually set it to 3200.
The BIOS says it is running at 3200 but memtest thinks it 3000mt/s.
Is memtest supposed to report what it is running at?

![20230714_020112](https://github.com/memtest86plus/memtest86plus/assets/303873/7bac10b6-6252-481c-984b-3c84e9de7ee0)

**Comment by debrouxl** [comment]
The memtest86+ 6.20 release version you're using does indeed not contain support for reading the IMC's registers in order to report the real memory frequency.
However, the in-development version, for which nightly binary builds can be downloaded from https://www.memtest.org/dev , contains tested IMC reading code for a number of recent desktop Intel (most Core i*) and AMD (Zen 1-4) processor models. The Ryzen 5 5600 belongs to the "Vermeer" Zen 3 series, so it should now be supported.

**Comment by bjlockie** [comment]
Great, it works.

It still displays v6.20 for the version, shouldn't that be v6.21 or 
something?

**Comment by debrouxl** [comment]
Indeed, so far, using different version numbers for in-development versions hasn't been done for memtest86+ 6.x hosted on Github, whereas some other projects do it. That may be partially because the Git commit hash prefix makes it possible to distinguish the 6.20 release from 6.20 + newer commits anyway. I don't know.
