### ISSUE TITLE
2017 Apple MacBook Pro claims to not support MemTest86+

### ISSUE THREAD

**Issue by novaTopFlex** [memtest86plus/memtest86plus#390]
My computer claims that UEFI is not compatible with MemTest86+, including the 64-bit version. However, I was successful when attempting the same on a QEMU virtual machine of the UEFI generation. What is the problem, and are most PCs newer than 2010 "too new" for MemTest86+?

**Comment by debrouxl** [comment]
Well... By now, memtest86+ was successfully tested on dozens, if not hundreds of physical UEFI platforms by beta-testers alone. It even showed bugs in some UEFI implementations, per #34 .
Another way to look at things is that if memtest86+'s UEFI support failed to work on most PCs newer than 2010, we'd have heard about it much earlier, and most of all, very much more frequently :)

Even though we've already received a report of Apple firmware being broken on a model older than yours ( #340 ), I'm not going to summarily brush off your report.
To begin with, does that model mandate the usage of Secure Boot ? Since the aforementioned #34 was merged, memtest86+ supports all of the technical pieces for SB signing; however, official memtest86+ binaries are not signed with the Microsoft key or any other vendor key which would be trusted by your computer's UEFI BIOS.
