### ISSUE TITLE
Whether support Arm？

### ISSUE THREAD

**Issue by changpenghui616** [memtest86plus/memtest86plus#391]
its seem look have a discuss about this isue #147 ， whether support run at arm plat now？

**Comment by debrouxl** [comment]
Nothing new since #147 and the issues linked there: for maintainers to implement a capability to run on other ISAs, access to suitable platforms, and available time to gain the appropriate knowledge, develop, and test changes, remain major roadblocks. On the maintainer side, I don't expect the situation to change in the foreseeable future.
For people on the payroll of ARM- or RISC-V-based hardware vendors, or major Linux distro vendors, who have access to suitable platforms and possess the appropriate low-level knowledge of the target platforms, I don't expect porting memtest86+ to other ISAs to be a difficult, highly time-consuming endeavour :)

While several recent server-class ARM and RISC-V platforms have ACPI and an UEFI BIOS, which is likely to make it easier to adapt memtest86+ to such platforms, the vast majority of ARM and RISC-V platforms do not have such firmware.

**Comment by debrouxl** [comment]
Support for UEFI LoongArch64 has now materialized as a pull request ( #410 ), after being worked on for a little while by a LoongArch maintainer ( #403 ). Chances are that some of the small architecture-independent bits contained in this PR will be integrated before the integration of the full PR.
Now it's the turn of vendors of UEFI AArch64 or RV64 platforms to port memtest86+ there :)

**Comment by x86fr** [comment]
Aarch64 support in #626
