### ISSUE TITLE
memtest86 bootable USB not loading, black screen and blinking cursor 

### ISSUE THREAD

**Issue by Argorix** [memtest86plus/memtest86plus#399]
- Motherboard model number: X570 Phantom Gaming 4 (256Mb AMI UEFI Legal BIOS with GUI support)
- BIOS version: American Megatrends Inc. P1.70, 10.09.2019.
- CPU: Ryzen 7 2700X, 3.7GHz, 16 MB, BOX (YD270XBGAFBOX)
USB not loading, black screen and blinking cursor

**Comment by debrouxl** [comment]
Thanks for your report.
In addition to the useful information you've posted, in order to be able to help you better, I think that it would be useful to know, for instance:
* the version of memtest86+ you're using;
* whether you're booting in legacy (CSM) or UEFI mode on your UEFI-capable BIOS;
* which tool you used to write the memtest86+ image on your USB storage;
* whether you can boot other OS (any modern Linux LiveCD will do) from your USB storage on your computer.

Thanks in advance :)

**Comment by Argorix** [comment]
1. I am using mt86plus_7.00_USB_Installer.
2. I don't know - how to find out this?
3. I did everything as in installer tutorial
4. oh no, it's too complicated

But when I am doing prime95 processor stress test my screen goes black, and this is a problem I am diagnose. If prime95 gives such results it can be a PC power supply problem rather that memory - as I think. What do you think?

**Comment by BurlyVik** [comment]
I think it's your process on how you are burning the image to your medium. Had no problems creating a USB image I'm currently running right now as my g-skill memory is shot. You might want to reevaluate how you are creating this image, there's nothing wrong with this release. Check your process.

**Comment by Argorix** [comment]
Ok, I will try.

**Comment by Argorix** [comment]
Oh, now I see that when I plug in USB flash, and it is already formated it shows two drives. One is USB (G:) and a second is MT86PLUS (H:). Should it be like this?

**Comment by BurlyVik** [comment]
> Oh, now I see that when I plug in USB flash, and it is already formated it shows two drives. One is USB (G:) and a second is MT86PLUS (H:). Should it be like this?

You need to check this from the BIOS. If you're running UEFI you need to go into the advanced settings, and click on boot at the top. When in boot the boot manager will display available devices on your system. Knowing which one is up to you. You have to cycle between each one in the hopes that there is a bootable image. Letter drives with Collins don't mean much to a bios. Trial and error

**Comment by Argorix** [comment]
I have only two options and choosing USB drive it doesn't start. Windows starts instead of the USB.

![IMG20240505163204](https://github.com/memtest86plus/memtest86plus/assets/141662994/e8f8c6ee-71ce-45e9-b2f6-40ccaa374697)

**Comment by BurlyVik** [comment]
> I have only two options and choosing USB drive it doesn't start. Windows starts instead of the USB.
> 
> ![IMG20240505163204](https://github.com/memtest86plus/memtest86plus/assets/141662994/e8f8c6ee-71ce-45e9-b2f6-40ccaa374697)
> 

Then there is a likelihood that the boot manager within the BIOS is not detected a bootable image. With that being said, you may have burned the image incorrectly on your USB. USB. You could have burned the actual binary file, instead of expanding the image using the program. Generally, when creating an image on a USB, the files are expanded. You'll see a variety of files including folders if done correctly. Generally, you'll see an EFI folder if done correctly on the USB. I would redownload the most current version of memtest 86 plus and then run it as is. It will generally pop up with a dialogue asking you to select a USB device, and there should be a box checked potentially to reformat it . 

It is rather straightforward, the program does the rest. Assuming your USB is plugged in and functional?

**Comment by debrouxl** [comment]
For Windows users, mt86plus_7.00_USB_Installer.exe is the most official way to write a bootable version of memtest86+ onto a USB MSD, right. It usually does its job.
You _could_ try to use Rufus instead, in order to write the ISO contained in the "Linux ISO (64 bits)" (mt86plus_7.00_64.iso.zip) and "Linux ISO w/ GRUB (64 bits)" (mt86plus_7.00_64.grub.iso.zip). Make sure to use the dd mode, as that ISO is already hybrid, i.e. suitable for direct USB boot. No need for Rufus or a similar tool (Unetbootin, BalenaEtcher, etc.) to interfere with the image's contents and break the ability to boot - I've already seen that happen.

For the record, the Rufus dd method is exactly the same for a Linux ISO (e.g. Debian, Ubuntu) as for a memtest86+ ISO - not any more difficult ;)
And deleting the partitions is something that the memtest86+ USB installer or Rufus already do correctly.

**Comment by Argorix** [comment]
Ok it worked! Yes, it was a problem with partitions. Tkanks.

**Comment by martinwhitaker** [comment]
This appears to have been solved, so closing.
