### ISSUE TITLE
Still black screen with Systemd-boot when booting the .efi file

### ISSUE THREAD

**Issue by xcom169** [memtest86plus/memtest86plus#434]
Hello all,

I took the latest release's .efi file and boot it with systemd-boot however I received a black screen and the computere froze. 
I also tried to disable secure boot but nothing changed. 
Are you sure it's fixed in the latest release?  I know it was an older issue.

I use x64 Arch Linux.
MB: https://www.asrock.com/mb/AMD/A620M-HDVM.2+/index.asp#BIOS
UEFI version : 3.06
CPU: AMD Ryzen 7600x
Memory 2 *  	Kingston fury beast 8 Gb DDR5 set to 5200 Mhz

**Comment by debrouxl** [comment]
Hello, thanks for the report. Yes, some display issues on were fixed in the past.
* please give us some information about the computer's hardware: computer model, processor model, RAM type and speed, this sort of things :)
* have you tried the EFI file from the nightly build downloadable from https://memtest.org/dev ?
* do the release and nightly install media from memtest.org, which do not use systemd-boot, successfully boot and display anything on the screen ?

The EFI file isn't signed with MS's key or any other key that your computer would have trusted out of the box, so you needed to disable SB anyway.

**Comment by xcom169** [comment]
Nightly version is working fine without SB !

**Comment by debrouxl** [comment]
Good. Then, I can close this issue :)
