### ISSUE TITLE
About the EHCI exit status when no EHCI device found

### ISSUE THREAD

**Issue by kilaterlee** [memtest86plus/memtest86plus#472]
The current EHCI driver sets the EHCI controller to EHC mode by default and does not revert to OHCI mode when no device is found. Is this correct?
![image](https://github.com/user-attachments/assets/1ed65fbe-4839-4220-bec3-e1ebeb2f8548)

I think when the device cannot be found on the ECHI controller, it should be restored to OHCI mode, because most of the EHCI and OHCI controllers are mixed together. I have tried it on Loongson 7A2000. If the EHC mode is set, the OHCI controller cannot be used.

**Comment by martinwhitaker** [comment]
If you look at the `find_usb_keyboards()` function in `usbhcd.c`, you will see it performs two passes. On the first pass it probes devices attached to EHCI controllers and on the second pass it probes devices attached to other types of controller.

The EHCI driver probes each of its ports. If it detects a low or full speed device on a port, it releases that port for use by a companion controller (UHCI or OHCI) by setting the `Port Owner` bit in the EHCI `PORTSC` register. So that port is then attached to the companion controller during the second pass of `find_usb_keyboards()` .

If you have a quirky EHCI controller that does not support port handover, you can use the `noehci` boot command line option. This is currently undocumented, as it hasn't been found necessary on x86 platforms since my last rework of the EHCI driver.

**Comment by kilaterlee** [comment]
OK.
