### ISSUE TITLE
Increased code size causes startup to hang on ASUS X205TA

### ISSUE THREAD

**Issue by martinwhitaker** [memtest86plus/memtest86plus#52]
This was introduced by commit be9502a : Add detection for Rambus RDRAM modules & support for ICH1/2/3, specifically this part:
````
+                case 0x01: // RAMBUS - RDRAM
+                    if (get_spd(index, spdidx, 1) == 8) {
+                        curspd = parse_spd_rdram(index, spdidx);
+                    }
+                    break;
````
This is an Intel Bay Trail machine with 32-bit EFI, so I'm using the 32-bit binary. Output of `lspci -nn` is
````
00:00.0 Host bridge [0600]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series SoC Transaction Register [8086:0f00] (rev 0f)
00:02.0 VGA compatible controller [0300]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display [8086:0f31] (rev 0f)
00:14.0 USB controller [0c03]: Intel Corporation Atom Processor Z36xxx/Z37xxx, Celeron N2000 Series USB xHCI [8086:0f35] (rev 0f)
00:1a.0 Encryption controller [1080]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Trusted Execution Engine [8086:0f18] (rev 0f)
00:1f.0 ISA bridge [0601]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Power Control Unit [8086:0f1c] (rev 0f)
````
Here is the [output of dmidecode](https://github.com/memtest86plus/memtest86plus/files/8546687/dmidecode.txt).

**Comment by martinwhitaker** [comment]
However, further investigation shows it's actually a code size problem. That commit must have just pushed it over a limit.

**Comment by debrouxl** [comment]
With #49 , it's the second time in two days that an increase in code size corresponding to expanded functionality causes issues :'(
The raw memtest.bin file for current memtest86+ 6.00-pre remains significantly smaller than that contained in the memtest86+ 5.31b package, but e.g. the BSS size is probably larger, even on low core count computers.

We should probably still merge #24 as a first step, because in #49 , in the current state of the code, it was shown to save a 4 KB memory page :)
The further step of optimization I outlined in the comments can be performed later. It will be less effective, but still.

**Comment by martinwhitaker** [comment]
In this case it was a real bug in the 32-bit startup code, so it's good to have found it.
