### ISSUE TITLE
ECC / EDAC support

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#91]
Memtest86+ needs to handle ECC / EDAC to properly support testing ECC memory.

Otherwise, bad memory may end up being reported as good due to errors being masked by the ECC mechanism.

**Comment by danielstr007** [comment]
Yes - EDAC, ECC-Event reporting support would be nice, on server systems with activated ECC we have to check the manufacture system event logs to see if ECC errors happen.
~ This is okay, as far as you know that you have to look at system logs. 
The memtest screen keeps "clean", because events are masked by ECC/BIOS mechanism.
